### PR TITLE
Makes generateID scoped's public member, added strategy for test env

### PR DESCRIPTION
**Pull request by kolodziejczakM**
Resolving #23

### CODE REVIEW

**Comment by kolodziejczakM** [comment]
Of course, I'll append test to it :)

**Comment by halcaponey** [comment]
Good work. I think the README should be updated to describe the new behavior.

**Comment by kolodziejczakM** [comment]
Thanks :) Of course I'll update the README.

**Comment by kolodziejczakM** [comment]
Ok, README is now updated. @halcaponey @sadick254

**Comment by kolodziejczakM** [comment]
When do you plan to merge it?

**Pull request merged**
