### PR TITLE
Fix failing build

### PR DESCRIPTION
**Pull request by halcaponey**
Used `let` by mistake, replaced it with `var`.

### CODE REVIEW

**Comment by halcaponey** [comment]
Sorry, I'll PR from my fork from now on.

**Comment by sadick254** [comment]
Now that you are a contributer to this repo. When you want to work on something, you branch off `master` to your `new branch` do some work and then open a PR. You don't have to work from your fork. You can work directly in this repo. I honestly think you are doing an amazing job with your contributions.

**Comment by halcaponey** [comment]
Why haven't you published the recent changes on npm ?

**Comment by sadick254** [comment]
I have been a little busy with work. I will definitely do it today.

**Comment by sadick254** [comment]
I have published the recent changes to `npm` now. 😃

**Pull request merged**
